use_frameworks!

platform :ios, '8.0'

target 'CloudFrontSignedURL_Example' do
  pod 'CloudFrontSignedURL', :path => '../'

  target 'CloudFrontSignedURL_Tests' do
    inherit! :search_paths

    
  end
end
